@startuml

actor User
participant RetSimulator
participant RetDriver
database DB

note over RetSimulator, RetDriver
DUMMY_SCAN_FRAME = "7e ff bf 81 f0 8 1 2 33 33 3 2 ff ff 13 37 7e "
ADDRESS_ASSIGNMENT_FRAME =
        "7e ff bf 81 f0 1b 1 13 41 4e "
        "30 30 30 30 43 4e 31 30 31 32 "
        "33 33 32 32 34 36 31 2 1 3 4 1 1 13 37 7e "
UA_FRAME = "7e 03 73 13 37 7e "
end note

group SetRetCommunicationAddress

User -> RetSimulator : put /IOPaths_1 /Ret_1
RetSimulator -> DB : create /IOPaths_1{bufferToSend=/Ret_1}

note over RetSimulator
Start listenning on the ICP:/Ret_1
end note

end group

== L1 Physical layer ==


loop 6 times every 300ms
    RetDriver -> RetSimulator : DummyScan /Ret_1
end

== L2 Data link layer ==

RetDriver -> RetSimulator : AddressAssignment(PreviouslyDetectedTask)
RetSimulator -> RetSimulator : **AddressAssignment**
RetDriver -> RetSimulator : SNRM
RetSimulator -> RetDriver : UA
RetSimulator -> RetSimulator : **Connected**

RetDriver -> RetSimulator : XID::ReleaseVersion
RetDriver -> RetSimulator : XID::AISGProtocolVersion

@enduml